name: primer-action

on: 
    workflow_dispatch:
    
jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo "step1"
        - name: step2
          run: echo "step2"
    job2:
        name: job2
        runs-on: ubuntu-latest
        steps:
        - name: github-action
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'Usando un action'
            color: 'gray'